
Testing compiled code...
Database opened successfully

Dump
====
 Persons: 3 (is_empty = 0)
  1: Rémi 2
  2: Norbert 2
  3: Alexandre 1

 Cities: 2
  1: Paris
  2: Lille


Dump
====
 Persons: 0 (is_empty = 1)

 Cities: 0


Dump
====
 Persons: 3 (is_empty = 0)
  1: Toto 2
  2: Évariste 0
  3: Catherine 0

 Cities: 4
  1: Barcelona
  2: New York
  3: Paris
  4: Tokyo

first: 1: Barcelona
last: 4: Tokyo
Trying to update into a duplicate Paris: ...
city_by_name unique index failure: ("Paris") at id = 2 was already at id = 3

Dump
====
 Persons: 3 (is_empty = 0)
  1: Toto 2
  2: Évariste 0
  3: Catherine 0

 Cities: 4
  1: Barcelona
  2: New York
  3: Paris
  4: Tokyo


Validity + get_at:
Paris
0: invalid!
1: Barcelona
2: New York
3: invalid!
4: Tokyo
5: invalid!
6: invalid!
7: invalid!
8: invalid!
9: invalid!

Dump
====
 Persons: 5 (is_empty = 0)
  1: Toto 2
  2: Évariste 0
  3: Catherine 0
  4: Toto 4
  5: Toto 1

 Cities: 3
  1: Barcelona
  2: New York
  4: Tokyo

Finding all Totos:
 1: New York
 4: Tokyo
 5: Barcelona
No Totox in the database
(begin != end) = 1
empty = 0
count = 3
range.size() = 3
Found Catherine!
Found Catherine!
Comment allez-vous?
Sorting with explicit sort:
Albert
Catherine
Toto
Toto
Toto
Zoé
Évariste
Sorting with index:
Albert
Catherine
Toto
Toto
Toto
Zoé
Évariste
Reverse order of cities:
Washington
Tokyo
New York
Beijing
Barcelona
id in table_with_no_field: 1
W == B: 0
W != B: 1
W < B: 1
W <= B: 1
W > B: 0
W >= B: 0
B == B: 1
B != B: 0
B < B: 0
B <= B: 1
B > B: 0
B >= B: 1
v1 opened
This joedb file has an old schema, and must be upgraded first.
OK: v2 refuses to open v1 readonly.
v1 re-opened
v2 opened
v2 re-opened
Trying to open a file with incompatible schema
OK: v1 code does not open v2 file
Trying to open a file with incompatible schema
OK: v1 code does not open v2 file
comment "Automatic schema upgrade"
create_table person
add_field person name string
comment "End of automatic schema upgrade"
insert_into person 1
update person 1 name "Toto"
insert_into person 2
update person 2 name "Rémi"
comment "This is a comment"
timestamp 12345 1970-01-01 03:25:45 GMT
comment "Automatic schema upgrade"
create_table language
add_field language name string
add_field language id string
add_field person preferred_language references language
custom set_default_preferred_language_to_english
add_field person height float32
insert_into language 1
update language 1 name "English"
update language 1 id "en"
update person 1 preferred_language 1
update person 2 preferred_language 1
comment "End of automatic schema upgrade"
v[0] = 0
v[1] = 0.1
v[2] = 0.2
v[3] = 0.3
v[4] = 0.4
empty size = 0
first().get_id() = 1
last().get_id() = 5
v[0] = {0, 1.234}
v[1] = {0.1, 1.234}
v[2] = {0.2, 1.234}
v[3] = {0.3, 1.234}
v[4] = {0.4, 1.234}
Testing exceptions...
city_by_name unique index failure: ("Paris") at id = 3 was already at id = 1
person_by_full_name unique index failure: ("Rémi", "Coulom") at id = 6 was already at id = 2
Duplicate insert into table city
insert_into: too big
insert_vector: null record_id, or too big
Paris
Failed reading a deleted row
Double delete
Invalid update
Checkpoints...
0
0
11
0
Toto
Évariste
Toto
Évariste
Toto
Hello
Bonjour
Hello
Bonjour
Hello
Rémi
Norbert
Alexandre
Rémi
Norbert
Alexandre
